---
active_modules: [pygments, tags, blog]
canonical_url: 'https://jachinlin.github.io'
author: Jachin Lin
title:  一叶知秋
modules:
  pygments:
    style: tango
github: jachinlin
email: linjx1000+github@gmail.com
baidu_tongji: 7972bc564f84e320d4f261fe1ada61da
nav:
  - title: 极客时间
    link: /geektime_dl
  - title: 每日一题
    link: /leetcode