name: Docs

on:
  push:
    branches:
    - master

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/jachinlin/blogme.git
    - name: Build project
      run: |
        blogme build
    - name: Upload gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./_build
        external_repository: jachinlin/jachinlin.github.io
        publish_branch: master
        commit_message: ${{ github.event.head_commit.message }}

